### ISSUE TITLE
What's the difference between id_columns and static_categorical_columns ?

### ISSUE THREAD

**Issue by IsaacWang-Ch** [ibm-granite/granite-tsfm#156]
Thank you and your team for the outstanding work. Congratulations on a job well done!

I'm a student working on time series forecasting for financial data, and I'm a bit confused about the difference between id_columns and static_categorical_columns. If I have a dataset containing multiple instruments, each with its own time series, should the Instrument column be configured as id_columns or static_categorical_columns?

**Comment by wgifford** [comment]
Thank you for your interest @IsaacWang-Ch.

If you have multiple series in a single dataframe you should specify the `id_column` in dataset / time series preprocessor instantiation. This allows the tensors to be created in such a way that a single context window will not span multiple series. The ID is only used for the context / prediction window generation and is not consumed by the model directly.

If you also want to pass the series ID to the model as a static categorical feature, you will need to specify it explicitly. If you add a static categorical feature, you will need to fine tune the model so that it can take advantage of the additional information.

**Comment by IsaacWang-Ch** [comment]
That was a very clear explanation! Thank you so much for your helpful response! @wgifford

**Comment by IsaacWang-Ch** [comment]
That was a very clear explanation! Thank you so much for your helpful response!
